--- #YAML:1.0
name:                Catalyst-Plugin-CRUD
version:             0.17
abstract:            CRUD (create/read/update/delete) Plugin for Catalyst
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Trigger:                0.1
    Jcode:                         2.05
    XML::Simple:                   2.14
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jun Shimizu <bayside@cpan.org>
