# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-CRUD
version:      0.08
version_from: lib/Catalyst/Plugin/CRUD.pm
installdirs:  site
requires:
    Class::Trigger:                0.1
    Jcode:                         2.05
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
