# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-CRUD
version:      0.21
version_from: lib/Catalyst/Plugin/CRUD.pm
installdirs:  site
requires:
    Class::Trigger:                0.08
    Jcode:                         2.05
    Scalar::Util:                  1.14
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
